Write-Host "The PowerShell installer has been retired."
Write-Host ""
Write-Host "Use the POSIX installer from Git Bash, MSYS2, Cygwin, or WSL:"
Write-Host ""
Write-Host "  curl -fsSL https://raw.githubusercontent.com/enxilium/enx-cli/main/scripts/install.sh | sh"
Write-Host ""
throw "Use scripts/install.sh from a POSIX shell."
